
[project]
name = "kaggle-clean"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pandas",
  "scikit-learn",
  "matplotlib",
  "seaborn",
  "joblib",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
